env:
  MANIFEST: https://github.com/ArrowOS/android_manifest.git
  MANIFEST_BRANCH: arrow-13.0
  DEVICE: Mi439
  OEM: xiaomi
  DT_LINK: https://github.com/ArrowOS-Mi439/android_device_xiaomi_Mi439.git -b arrow-13.0
  DT_PATH: device/$OEM/$DEVICE
  VT_LINK: https://github.com/Mi-Thorium/proprietary_vendor_xiaomi_Mi439.git -b a11/master
  VT_PATH: vendor/$OEM/$DEVICE
  VT_CO_PATH: vendor/xiaomi/mithorium-common
  KT_LINK: https://github.com/ArrowOS-Mi439/android_kernel_xiaomi_sdm439.git -b arrow-13.0
  KT_PATH: kernel/$OEM/$DEVICE
  CO_LINK: https://github.com/ArrowOS-Mi439/android_device_xiaomi_mithorium-common.git -b arrow-13.0
  CO_PATH: device/xiaomi/mithorium-common
  LUNCH_COMBO: arrow_Mi439-userdebug
  TARGET: bacon
  OUTPUT: Arrow*.zip

  # Not Recommended to Change
  SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
  CCACHE_SIZE: 30G
  CCACHE_DIR: $HOME/work/.ccache
  J_VAL: 16

  # Cirrus Specific Vars (Do *NOT* Change)
  CIRRUS_SHELL: bash

task:
  name: "Arrowos Build"
  timeout_in: 4h
  container:
    image: apon77/aosp:cirrus
    cpu: 8
    memory: 16G

  Storage_Checker:
    - df -h
    - lsblk
    - ls -l -a -h

  Sync_script:
    - bash sync.sh

  Build_script:
    - bash build.sh

  Upload_script:
    - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
    - bash upload.sh
